# Generated by Django 4.2.29 on 2026-04-04 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('numero_toma', models.CharField(max_length=30, unique=True)),
                ('ubicacion', models.TextField(blank=True)),
                ('costo_anual', models.DecimalField(decimal_places=2, default=800, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('ciudadano', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toma', to='core.ciudadano')),
            ],
            options={
                'verbose_name': 'Toma',
                'verbose_name_plural': 'Tomas',
                'ordering': ['numero_toma'],
            },
        ),
    ]
