# Generated by Django 4.2.29 on 2026-07-31 19:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('edad', models.PositiveSmallIntegerField()),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('numero_contrato', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. de contrato')),
                ('labor_social', models.TextField(blank=True, verbose_name='Labor social')),
                ('motivo_alta', models.CharField(blank=True, choices=[('ESTUDIOS', 'Conclusión o interrupción de estudios'), ('MAYORIA_EDAD', 'Mayoría de edad'), ('INTEGRACION_COMUNIDAD', 'Integración voluntaria a la comunidad')], max_length=22, verbose_name='Motivo de alta')),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '🧑 Ciudadano',
                'verbose_name_plural': '🧑 Ciudadanos',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('clave', models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La clave solo puede contener letras, números o guiones.', regex='^[A-Za-z0-9-]+$')], verbose_name='Clave')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('responsable', models.ForeignKey(blank=True, help_text='El responsable debería pertenecer normalmente a la manzana que representa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manzanas_a_cargo', to='core.ciudadano', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Manzana',
                'verbose_name_plural': 'Manzanas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='manzana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciudadanos', to='core.manzana', verbose_name='Manzana'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['edad'], name='core_ciudad_edad_1bf570_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['apellido_paterno', 'apellido_materno', 'nombre'], name='core_ciudad_apellid_95ba1d_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['manzana', 'activo'], name='ciud_manz_act_idx'),
        ),
    ]
