# Generated by Django 4.2.30 on 2026-08-01 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciudadano",
            name="sexo",
            field=models.CharField(
                choices=[
                    ("HOMBRE", "Hombre"),
                    ("MUJER", "Mujer"),
                    ("NO_ESPECIFICADO", "No especificado"),
                ],
                default="NO_ESPECIFICADO",
                max_length=20,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="edad",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(130)],
                verbose_name="Edad registrada",
            ),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="fecha_nacimiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de nacimiento"
            ),
        ),
    ]
