# Generated by Django 4.2.29 on 2026-05-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_replace_curp_with_edad'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ciudadano',
            new_name='core_ciudad_edad_1bf570_idx',
            old_name='core_ciudad_edad_362f20_idx',
        ),
    ]
