# Generated by Django 4.2.29 on 2026-06-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ciudadano_options'),
        ('core', '0004_merge_20260519_2112'),
    ]

    operations = [
    ]
