# Generated by Django 4.2.30 on 2026-07-29 21:39

from django.db import migrations, models
import django.db.models.deletion


def archivar_telefonos(apps, schema_editor):
    Ciudadano = apps.get_model("core", "Ciudadano")
    TelefonoLegado = apps.get_model("core", "TelefonoCiudadanoLegado")
    registros = [
        TelefonoLegado(ciudadano_id=ciudadano.pk, valor=ciudadano.telefono)
        for ciudadano in Ciudadano.objects.exclude(telefono="")
    ]
    TelefonoLegado.objects.bulk_create(registros, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_merge_20260615_1038"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manzana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Manzana",
                "verbose_name_plural": "Manzanas",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="ciudadano",
            name="labor_social",
            field=models.TextField(blank=True, verbose_name="Labor social"),
        ),
        migrations.AddField(
            model_name="ciudadano",
            name="motivo_alta",
            field=models.TextField(blank=True, verbose_name="Motivo de alta"),
        ),
        migrations.AddField(
            model_name="ciudadano",
            name="numero_contrato",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="No. de contrato"
            ),
        ),
        migrations.CreateModel(
            name="TelefonoCiudadanoLegado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.CharField(max_length=20)),
                ("archivado_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ciudadano",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telefono_legado",
                        to="core.ciudadano",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teléfono legado de ciudadano",
                "verbose_name_plural": "Teléfonos legados de ciudadanos",
            },
        ),
        migrations.RunPython(archivar_telefonos, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="ciudadano",
            name="telefono",
        ),
        migrations.AddField(
            model_name="ciudadano",
            name="manzana",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ciudadanos",
                to="core.manzana",
            ),
        ),
    ]
