# Generated by Django 4.2.30 on 2026-07-30 13:37

from django.db import migrations, models


MOTIVOS_VALIDOS = {"ESTUDIOS", "MAYORIA_EDAD", "INTEGRACION_COMUNIDAD"}


def revisar_motivos_alta_existentes(apps, schema_editor):
    """Detiene la migración antes de alterar datos libres que requieren revisión."""
    Ciudadano = apps.get_model("core", "Ciudadano")
    valores_desconocidos = list(
        Ciudadano.objects.exclude(motivo_alta="")
        .exclude(motivo_alta__in=MOTIVOS_VALIDOS)
        .order_by("motivo_alta")
        .values_list("motivo_alta", flat=True)
        .distinct()
    )
    if valores_desconocidos:
        raise RuntimeError(
            "La migración no modificó motivo_alta. Revise y clasifique primero "
            f"estos valores existentes: {valores_desconocidos!r}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_manzana_remove_ciudadano_telefono_and_more"),
    ]

    operations = [
        migrations.RunPython(
            revisar_motivos_alta_existentes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="motivo_alta",
            field=models.CharField(
                choices=[
                    ("ESTUDIOS", "Conclusión o interrupción de estudios"),
                    ("MAYORIA_EDAD", "Mayoría de edad"),
                    ("INTEGRACION_COMUNIDAD", "Integración voluntaria a la comunidad"),
                ],
                max_length=22,
                verbose_name="Motivo de alta",
            ),
        ),
    ]
