# Generated by Django 4.2.30 on 2026-07-31 18:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_ciudadano_motivo_alta"),
    ]

    operations = [
        migrations.AddField(
            model_name="manzana",
            name="clave",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La clave solo puede contener letras, números o guiones.",
                        regex="^[A-Za-z0-9-]+$",
                    )
                ],
                verbose_name="Clave",
            ),
        ),
        migrations.AddField(
            model_name="manzana",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                help_text="El responsable debería pertenecer normalmente a la manzana que representa.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manzanas_a_cargo",
                to="core.ciudadano",
                verbose_name="Responsable",
            ),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="manzana",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ciudadanos",
                to="core.manzana",
                verbose_name="Manzana",
            ),
        ),
        migrations.AlterField(
            model_name="manzana",
            name="activa",
            field=models.BooleanField(default=True, verbose_name="Activa"),
        ),
        migrations.AlterField(
            model_name="manzana",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="manzana",
            name="nombre",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nombre"),
        ),
        migrations.AddIndex(
            model_name="ciudadano",
            index=models.Index(fields=["manzana", "activo"], name="ciud_manz_act_idx"),
        ),
    ]
