# Generated by Django 4.2.29 on 2026-07-31 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacion', '0001_initial'),
        ('comites', '0001_initial'),
        ('core', '0001_initial'),
        ('agua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('naturaleza', models.CharField(choices=[('PAGO', 'Pago'), ('COOPERACION', 'Cooperación')], max_length=20)),
                ('origen', models.CharField(choices=[('TESORERIA', 'Tesorería'), ('FAENA', 'Faena'), ('JUNTA', 'Junta'), ('AGUA', 'Agua')], default='TESORERIA', max_length=20)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('monto_individual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('anio_periodo', models.PositiveIntegerField(blank=True, null=True)),
                ('registros_generados', models.BooleanField(default=False)),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_tesoreria', to='comites.comite')),
            ],
            options={
                'verbose_name': 'Concepto de tesorería',
                'verbose_name_plural': 'Conceptos de tesorería',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('CUOTA_ANUAL', 'Cuota anual'), ('DEUDA_FAENA', 'Deuda de faena'), ('SERVICIO', 'Servicio'), ('CUOTA_COMITE', 'Cuota de comité'), ('OTRO', 'Otro')], default='CUOTA_COMITE', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=200)),
                ('anio_periodo', models.PositiveIntegerField(blank=True, null=True)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.ciudadano')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='comites.comite')),
                ('registro_faena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='operacion.registrofaena')),
                ('toma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='agua.toma')),
            ],
            options={
                'verbose_name': '💰 Pago',
                'verbose_name_plural': '💰 Pagos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObligacionCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_tesoreria', to='core.ciudadano')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones', to='tesoreria.conceptotesoreria')),
            ],
            options={
                'verbose_name': 'Obligación ciudadana',
                'verbose_name_plural': 'Obligaciones ciudadanas',
                'ordering': ['ciudadano__apellido_paterno', 'ciudadano__apellido_materno', 'ciudadano__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cooperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('ORDINARIA', 'Ordinaria'), ('EXTRAORDINARIA', 'Extraordinaria'), ('DONACION', 'Donación'), ('APOYO_EVENTO', 'Apoyo a evento')], default='ORDINARIA', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=200)),
                ('anio_periodo', models.PositiveIntegerField(blank=True, null=True)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperaciones', to='core.ciudadano')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperaciones', to='comites.comite')),
            ],
            options={
                'verbose_name': '💰 Cooperación',
                'verbose_name_plural': '💰 Cooperaciones',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('notas', models.TextField(blank=True)),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='tesoreria.obligacionciudadano')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='obligacionciudadano',
            constraint=models.UniqueConstraint(fields=('concepto', 'ciudadano'), name='unique_obligacion_por_concepto_ciudadano'),
        ),
    ]
