# Generated by Django 4.2.29 on 2026-04-04 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('operacion', '__first__'),
        ('comites', '0001_initial'),
        ('agua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('CUOTA_ANUAL', 'Cuota anual'), ('DEUDA_FAENA', 'Deuda de faena'), ('SERVICIO', 'Servicio'), ('CUOTA_COMITE', 'Cuota de comité'), ('OTRO', 'Otro')], default='CUOTA_COMITE', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=200)),
                ('anio_periodo', models.PositiveIntegerField(blank=True, null=True)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.ciudadano')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='comites.comite')),
                ('registro_faena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='operacion.registrofaena')),
                ('toma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='agua.toma')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cooperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipo', models.CharField(choices=[('ORDINARIA', 'Ordinaria'), ('EXTRAORDINARIA', 'Extraordinaria'), ('DONACION', 'Donación'), ('APOYO_EVENTO', 'Apoyo a evento')], default='ORDINARIA', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=200)),
                ('anio_periodo', models.PositiveIntegerField(blank=True, null=True)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperaciones', to='core.ciudadano')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperaciones', to='comites.comite')),
            ],
            options={
                'verbose_name': 'Cooperación',
                'verbose_name_plural': 'Cooperaciones',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
