# Generated by Django 4.2.29 on 2026-05-20 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperacion',
            options={'ordering': ['-fecha', '-created_at'], 'verbose_name': '💰 Cooperación', 'verbose_name_plural': '💰 Cooperaciones'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha', '-created_at'], 'verbose_name': '💰 Pago', 'verbose_name_plural': '💰 Pagos'},
        ),
    ]
