# Generated by Django 4.2 on 2026-07-31

from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("tesoreria", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="conceptotesoreria",
            name="alcance",
            field=models.CharField(
                choices=[("GENERAL", "Toda la comunidad"), ("MANZANA", "Por manzana")],
                default="GENERAL",
                max_length=15,
                verbose_name="Alcance",
            ),
        ),
        migrations.AddField(
            model_name="conceptotesoreria",
            name="manzana",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conceptos_tesoreria",
                to="core.manzana",
                verbose_name="Manzana",
            ),
        ),
        migrations.AlterField(
            model_name="conceptotesoreria",
            name="monto_individual",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddIndex(
            model_name="conceptotesoreria",
            index=models.Index(
                fields=["naturaleza", "alcance", "manzana", "fecha"],
                name="tes_nat_alc_mz_fecha_idx",
            ),
        ),
    ]
