# Generated by Django 4.2.29 on 2026-07-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_alter_cooperacion_options_alter_pago_options'),
        ('tesoreria', '0002_conceptotesoreria_alter_cooperacion_options_and_more'),
    ]

    operations = [
    ]
