# Generated by Django 4.2.29 on 2026-07-31 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('comites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='comites.comite')),
            ],
            options={
                'verbose_name': '📌 Actividad',
                'verbose_name_plural': '📌 Actividades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Faena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faenas', to='comites.comite')),
            ],
            options={
                'verbose_name': '🛠️ Faena',
                'verbose_name_plural': '🛠️ Faenas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Junta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('ORDINARIA', 'Ordinaria'), ('EXTRAORDINARIA', 'Extraordinaria'), ('INFORMATIVA', 'Informativa')], default='ORDINARIA', max_length=20)),
                ('lugar', models.CharField(blank=True, max_length=150)),
                ('tema', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juntas', to='comites.comite')),
            ],
            options={
                'verbose_name': '👥 Junta',
                'verbose_name_plural': '👥 Juntas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ActividadArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to='actividades/')),
                ('descripcion', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='operacion.actividad')),
            ],
            options={
                'verbose_name': 'Archivo de actividad',
                'verbose_name_plural': 'Archivos de actividades',
            },
        ),
        migrations.CreateModel(
            name='RegistroFaena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASISTIO', 'Asistió'), ('FALTO', 'Faltó'), ('JUSTIFICADO', 'Justificado')], default='PENDIENTE', max_length=20)),
                ('genera_adeudo', models.BooleanField(default=False)),
                ('monto_adeudo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_faena', to='core.ciudadano')),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='operacion.faena')),
            ],
            options={
                'verbose_name': 'Registro de faena',
                'verbose_name_plural': 'Registros de faena',
                'unique_together': {('faena', 'ciudadano')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaJunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASISTIO', 'Asistió'), ('FALTO', 'Faltó'), ('JUSTIFICADO', 'Justificado')], default='PENDIENTE', max_length=20)),
                ('genera_adeudo', models.BooleanField(default=False)),
                ('monto_adeudo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('asistio', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_junta', to='core.ciudadano')),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='operacion.junta')),
            ],
            options={
                'verbose_name': 'Asistencia a junta',
                'verbose_name_plural': 'Asistencias a juntas',
                'unique_together': {('junta', 'ciudadano')},
            },
        ),
    ]
