# Generated by Django 4.2.30 on 2026-07-31 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("operacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faena",
            name="alcance",
            field=models.CharField(
                choices=[("GENERAL", "Toda la comunidad"), ("MANZANA", "Por manzana")],
                default="GENERAL",
                max_length=15,
                verbose_name="Alcance",
            ),
        ),
        migrations.AddField(
            model_name="faena",
            name="manzana",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="faenas",
                to="core.manzana",
                verbose_name="Manzana",
            ),
        ),
        migrations.AddIndex(
            model_name="faena",
            index=models.Index(
                fields=["alcance", "manzana", "fecha"], name="faena_alc_manz_fecha_idx"
            ),
        ),
    ]
