# Generated by Django 4.2.29 on 2026-05-20 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['-fecha'], 'verbose_name': '📌 Actividad', 'verbose_name_plural': '📌 Actividades'},
        ),
        migrations.AlterModelOptions(
            name='faena',
            options={'ordering': ['-fecha'], 'verbose_name': '🛠️ Faena', 'verbose_name_plural': '🛠️ Faenas'},
        ),
        migrations.AlterModelOptions(
            name='junta',
            options={'ordering': ['-fecha'], 'verbose_name': '🤝 Junta', 'verbose_name_plural': '🤝 Juntas'},
        ),
    ]
