# Generated by Django 4.2.29 on 2026-05-20 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0002_alter_actividad_options_alter_faena_options_and_more'),
        ('operacion', '0002_registrofaena_pendiente_default'),
    ]

    operations = [
    ]
