# Generated by Django 4.2.30 on 2026-07-31 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("operacion", "0002_faena_alcance_faena_manzana_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="junta",
            name="alcance",
            field=models.CharField(
                choices=[("GENERAL", "Toda la comunidad"), ("MANZANA", "Por manzana")],
                default="GENERAL",
                max_length=15,
                verbose_name="Alcance",
            ),
        ),
        migrations.AddField(
            model_name="junta",
            name="manzana",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="juntas",
                to="core.manzana",
                verbose_name="Manzana",
            ),
        ),
        migrations.AddIndex(
            model_name="junta",
            index=models.Index(
                fields=["alcance", "manzana", "fecha"], name="junta_alc_manz_fecha_idx"
            ),
        ),
    ]
