# Generated by Django 4.2.29 on 2026-06-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0003_asistenciajunta_estatus'),
        ('operacion', '0003_merge_20260519_2151'),
    ]

    operations = [
    ]
