# Generated by Django 4.2.29 on 2026-07-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0004_junta_estado_asistenciajunta_adeudos'),
        ('operacion', '0004_merge_20260615_1038'),
    ]

    operations = [
    ]
