# Generated by Django 4.2.29 on 2026-07-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0005_merge_20260710_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='junta',
            options={'ordering': ['-fecha'], 'verbose_name': '👥 Junta', 'verbose_name_plural': '👥 Juntas'},
        ),
    ]
