from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from apps.core.views import (
    control_asistencias,
    control_agua,
    control_asistencias_faena_detalle,
    control_asistencias_junta_detalle,
    captura_asistencia_faena,
    captura_asistencia_junta,
    captura_asistencia_secuencial_faena,
    captura_asistencia_secuencial_junta,
    crear_ciudadano_operativo,
    editar_ciudadano_operativo,
    crear_faena_operativa,
    crear_junta_operativa,
    dashboard_operativo,
    exportar_ciudadanos_csv,
    generar_registros_faena,
    generar_registros_junta,
    editar_estado_evento,
    exportar_participantes_faena_csv,
    exportar_participantes_junta_csv,
    editar_faena_operativa,
    editar_junta_operativa,
    eliminar_faena_operativa,
    eliminar_junta_operativa,
    home,
    padron_ciudadanos,
    perfil_ciudadano,
    tesoreria_operativa,
    crear_concepto_tesoreria,
    eliminar_concepto_tesoreria,
    generar_obligaciones_tesoreria,
    tesoreria_concepto_detalle,
    acreditar_obligacion,
)

urlpatterns = [
    path('', home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dashboard/', dashboard_operativo, name='dashboard_operativo'),
    path('ciudadanos/', padron_ciudadanos, name='padron_ciudadanos'),
    path('ciudadanos/nuevo/', crear_ciudadano_operativo, name='crear_ciudadano_operativo'),
    path('ciudadanos/<int:pk>/editar/', editar_ciudadano_operativo, name='editar_ciudadano_operativo'),
    path('ciudadanos/exportar-csv/', exportar_ciudadanos_csv, name='exportar_ciudadanos_csv'),
    path('dashboard/ciudadano/<int:pk>/', perfil_ciudadano, name='perfil_ciudadano'),
    path('control-asistencias/', control_asistencias, name='control_asistencias'),
    path('agua/', control_agua, name='control_agua'),
    path('tesoreria/', tesoreria_operativa, name='tesoreria_operativa'),
    path('tesoreria/nuevo/', crear_concepto_tesoreria, name='crear_concepto_tesoreria'),
    path('tesoreria/conceptos/<int:pk>/editar/', crear_concepto_tesoreria, name='editar_concepto_tesoreria'),
    path('tesoreria/conceptos/<int:pk>/eliminar/', eliminar_concepto_tesoreria, name='eliminar_concepto_tesoreria'),
    path('tesoreria/conceptos/<int:pk>/', tesoreria_concepto_detalle, name='tesoreria_concepto_detalle'),
    path('tesoreria/conceptos/<int:pk>/generar-obligaciones/', generar_obligaciones_tesoreria, name='generar_obligaciones_tesoreria'),
    path('tesoreria/obligaciones/<int:pk>/acreditar/', acreditar_obligacion, name='acreditar_obligacion'),
    path('operacion/faenas/nueva/', crear_faena_operativa, name='crear_faena_operativa'),
    path('operacion/faenas/<int:faena_id>/editar/', editar_faena_operativa, name='editar_faena_operativa'),
    path('operacion/faenas/<int:faena_id>/eliminar/', eliminar_faena_operativa, name='eliminar_faena_operativa'),
    path('operacion/juntas/nueva/', crear_junta_operativa, name='crear_junta_operativa'),
    path('operacion/juntas/<int:junta_id>/editar/', editar_junta_operativa, name='editar_junta_operativa'),
    path('operacion/juntas/<int:junta_id>/eliminar/', eliminar_junta_operativa, name='eliminar_junta_operativa'),
    path('control-asistencias/faena/<int:faena_id>/', control_asistencias_faena_detalle, name='control_asistencias_faena_detalle'),
    path('control-asistencias/junta/<int:junta_id>/', control_asistencias_junta_detalle, name='control_asistencias_junta_detalle'),
    path('control-asistencias/faena/<int:faena_id>/exportar-csv/', exportar_participantes_faena_csv, name='exportar_participantes_faena_csv'),
    path('control-asistencias/junta/<int:junta_id>/exportar-csv/', exportar_participantes_junta_csv, name='exportar_participantes_junta_csv'),
    path('control-asistencias/faena/<int:faena_id>/captura/', captura_asistencia_faena, name='captura_asistencia_faena'),
    path('control-asistencias/junta/<int:junta_id>/captura/', captura_asistencia_junta, name='captura_asistencia_junta'),
    path('control-asistencias/faena/<int:faena_id>/captura-presencial/', captura_asistencia_secuencial_faena, name='captura_asistencia_secuencial_faena'),
    path('control-asistencias/junta/<int:junta_id>/captura-presencial/', captura_asistencia_secuencial_junta, name='captura_asistencia_secuencial_junta'),
    path('control-asistencias/<str:event_kind>/<int:event_id>/estado/', editar_estado_evento, name='editar_estado_evento'),
    path('dashboard/faena/<int:faena_id>/generar-registros/', generar_registros_faena, name='generar_registros_faena'),
    path('dashboard/junta/<int:junta_id>/generar-registros/', generar_registros_junta, name='generar_registros_junta'),
    path('admin/', admin.site.urls),
]
