# Generated by Django 4.2.29 on 2026-04-04 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('AGUA', 'Agua'), ('FERIA', 'Feria'), ('IGLESIA', 'Iglesia'), ('DELEGACION', 'Delegación')], default='DELEGACION', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Comité',
                'verbose_name_plural': 'Comités',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('rol', models.CharField(choices=[('DELEGADO', 'Delegado'), ('PRESIDENTE', 'Presidente'), ('TESORERO', 'Tesorero'), ('SECRETARIO', 'Secretario'), ('CAPTURISTA', 'Capturista'), ('LECTURA', 'Solo lectura')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('ciudadano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to='core.ciudadano')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='comites.comite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_app', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de acceso',
                'verbose_name_plural': 'Perfiles de acceso',
                'ordering': ['comite__nombre', 'rol'],
                'unique_together': {('user', 'comite', 'rol')},
            },
        ),
    ]
