# Generated by Django 4.2.30 on 2026-08-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comites", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comite",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("AGUA", "Agua"),
                    ("PANTEON", "Panteón"),
                    ("FERIA", "Feria"),
                    ("IGLESIA", "Iglesia"),
                    ("PEREGRINO", "Peregrino"),
                    ("CLINICA", "Clínica"),
                    ("PEREGRINACION", "Peregrinación"),
                    ("DELEGACION", "Delegación"),
                ],
                default="DELEGACION",
                max_length=20,
            ),
        ),
    ]
