# Generated by Django 4.2.29 on 2026-05-20 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comite',
            options={'ordering': ['nombre'], 'verbose_name': '🏛️ Comité', 'verbose_name_plural': '🏛️ Comités'},
        ),
    ]
